# Generated by Django 3.2.4 on 2021-07-29 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_subscribermodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribermodel',
            options={'verbose_name': 'Subscriber', 'verbose_name_plural': 'Subscriber'},
        ),
    ]
